# Generated by Django 5.2.6 on 2026-04-20 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('classification', 'Класифікація'), ('clustering', 'Кластеризація'), ('anomaly', 'Пошук аномалій')], max_length=20)),
                ('feature_set', models.CharField(choices=[('standard', 'Лише класичні ознаки'), ('fractal', 'Лише фрактальні ознаки'), ('combined', 'Комбінований набір ознак'), ('compare', 'Порівняти всі набори')], default='compare', max_length=20)),
                ('model_name', models.CharField(default='random_forest', max_length=100)),
                ('n_clusters', models.PositiveIntegerField(default=3)),
                ('window_size', models.PositiveIntegerField(default=64)),
                ('step_size', models.PositiveIntegerField(default=32)),
                ('smoothing_window', models.PositiveIntegerField(default=3)),
                ('normalize', models.BooleanField(default=True)),
                ('detrend', models.BooleanField(default=False)),
                ('fill_missing', models.BooleanField(default=True)),
                ('remove_outliers', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('running', 'Виконується'), ('completed', 'Завершено'), ('failed', 'Помилка')], default='pending', max_length=20)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='datasets.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
